name: Auto Scraper

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2:00 UTC; adjust as needed
  workflow_dispatch:      # Allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Use your required version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python run_scraper.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: scholarship-data
        path: scholarship_data/
