name: Auto Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List all files for debugging
      run: |
        pwd
        ls -al

    - name: List all files for debugging
      run: |
        pwd
        ls -al

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python run_scraper.py

    - name: Upload data to EC2 DB
      env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
      run: python db_upload.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: scholarship-data
        path: scholarship_data/
